### ISSUE TITLE
价格显示错误.

### ISSUE THREAD

**Issue by MengleBoot** [BobCoderS9/V2board-Argon#2]
一次性的产品都是为0.00元
![D09862F8-0BF4-41D3-A70B-AB4687F9D785](https://user-images.githubusercontent.com/60128804/127374183-a7da1467-a96f-4bf6-bd5d-d0a1df968955.png)

**Comment by hyjsos** [comment]
同理。如果套餐只有年付，没有月付也是显示为0

**Comment by BobCoderS9** [comment]
已修复
