### ISSUE TITLE
待支付订单无法点开进行支付或取消

### ISSUE THREAD

**Issue by hyjsos** [BobCoderS9/V2board-Argon#4]
在我的订单----订单列表里的订单。如果是待支付的订单。正常应该可以点开再次支付。或者点取消订单。不然用户得等到订单自然被取消后，才可下新订单。
![image](https://user-images.githubusercontent.com/34772779/127426417-b7955fe2-772a-4b4a-bb19-af6cc12cd966.png)

原版订单页面：![image](https://user-images.githubusercontent.com/34772779/127426466-bed96e99-1ca1-4d24-8102-27f60baa4010.png)

**Comment by BobCoderS9** [comment]
已修复
