### ISSUE TITLE
绑定tg无法显示出正确的tg_bot

### ISSUE THREAD

**Issue by hyjsos** [BobCoderS9/V2board-Argon#5]
![image](https://user-images.githubusercontent.com/34772779/127426943-7827196b-e574-4d51-90e6-b3649ac3f49f.png)
如上图：后台已经正确设置bot。但这里还是显示的为bob。/bind后面也无正确的绑定命令。

**Comment by BobCoderS9** [comment]
已修复

**Comment by hyjsos** [comment]
第一步是修复了。第2步 /bind 后面应该显示订阅链接才对。 v2board是通过订阅链接进行绑定tg的
